version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: medical_comparator_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: medical_comparator
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - medical_network

  backend:
    build: ./backend
    container_name: medical_comparator_backend
    environment:
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/medical_comparator?authSource=admin
      OPENAI_API_KEY: ${OPENAI_API_KEY:-your_openai_key_here}
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - ./data:/app/data
    networks:
      - medical_network

  frontend:
    image: nginx:alpine
    container_name: medical_comparator_frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - medical_network

volumes:
  mongodb_data:

networks:
  medical_network:
    driver: bridge