name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy bandit safety
        cd backend
        pip install -r requirements.txt
    
    - name: Auto-format with Black
      run: |
        black backend/app/ tests/
    
    - name: Auto-sort imports with isort
      run: |
        isort backend/app/ tests/
    
    - name: Commit formatting changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'style: auto-format code with black and isort'
        file_pattern: '*.py'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run code quality checks
      run: |
        # Check formatting
        black --check backend/app/ tests/
        
        # Check import sorting
        isort --check-only backend/app/ tests/
        
        # Linting
        flake8 backend/app/ tests/ --max-line-length=88 --extend-ignore=E203,W503
        
        # Type checking
        mypy backend/app/ --ignore-missing-imports
        
        # Security scanning
        bandit -r backend/app/
        
        # Dependency vulnerability check
        cd backend && safety check