name: Test Suite

on:
  push:
    branches: [ main, develop, copilot/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt
    
    - name: Create logs directory
      run: mkdir -p logs
    
    - name: Set environment variables
      run: |
        echo "TESTING=true" >> $GITHUB_ENV
        echo "LOG_LEVEL=ERROR" >> $GITHUB_ENV
    
    - name: Run tests with pytest
      run: |
        cd backend
        python -m pytest ../tests/ -v --cov=app --cov-report=xml --cov-report=term-missing
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install linting dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy
        cd backend
        pip install -r requirements.txt
    
    - name: Run Black
      run: |
        black --check --diff backend/app/ tests/
    
    - name: Run isort
      run: |
        isort --check-only --diff backend/app/ tests/
    
    - name: Run flake8
      run: |
        flake8 backend/app/ tests/ --max-line-length=88 --extend-ignore=E203,W503
    
    - name: Run mypy
      run: |
        mypy backend/app/ --ignore-missing-imports

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install security scanning tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
        cd backend
        pip install -r requirements.txt
    
    - name: Run Bandit security scan
      run: |
        bandit -r backend/app/ -f json -o bandit-report.json || true
        bandit -r backend/app/
    
    - name: Run Safety check
      run: |
        cd backend
        safety check --json --output safety-report.json || true
        safety check
    
    - name: Upload security reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
          backend/safety-report.json

  build-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker images
      run: |
        docker-compose build
    
    - name: Start services
      run: |
        docker-compose up -d
        sleep 30  # Wait for services to start
    
    - name: Test application health
      run: |
        curl -f http://localhost:8000/health || exit 1
        curl -f http://localhost:8000/ || exit 1
    
    - name: Test API endpoints
      run: |
        # Test providers endpoint
        curl -f http://localhost:8000/api/v1/providers/ || exit 1
        
        # Test analyses search
        curl -f "http://localhost:8000/api/v1/analyses/search?query=test" || exit 1
    
    - name: Stop services
      run: |
        docker-compose down
    
    - name: Clean up Docker
      run: |
        docker system prune -af